/* eslint-disable no-undef */

require('dotenv').config();

module.exports = {
	NODE_ENV: process.env.NODE_ENV?.trim(),

	PORT: process.env.PORT,

	DB_URL: process.env.DB_URL,

	SALT_ROUNDS: Number(process.env.SALT_ROUNDS),

	DESAFE_SUPER_ADMIN_PHONE: process.env.DESAFE_SUPER_ADMIN_PHONE,
	DESAFE_SUPER_ADMIN_PASSWORD: process.env.DESAFE_SUPER_ADMIN_PASSWORD,
	DESAFE_SUPER_ADMIN_FULLNAME: process.env.DESAFE_SUPER_ADMIN_FULLNAME,

	JWT_LOGIN_SECRET_KEY: process.env.JWT_LOGIN_SECRET_KEY,
	JWT_SIGNUP_SECRET_KEY: process.env.JWT_SIGNUP_SECRET_KEY,
	JWT_FORGOT_PASSWORD_SECRET_KEY: process.env.JWT_FORGOT_PASSWORD_SECRET_KEY,
	JWT_RESET_PASSWORD_SECRET_KEY: process.env.JWT_RESET_PASSWORD_SECRET_KEY,

	AWS_ENDPOINT: process.env.AWS_ENDPOINT,
	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	AWS_ACCESS_SECRET_KEY: process.env.AWS_ACCESS_SECRET_KEY,
	AWS_REGION: process.env.AWS_REGION,
	AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,

	TWILIO_SID: process.env.TWILIO_SID,
	TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
	TWILIO_SERVICE: process.env.TWILIO_SERVICE,
};
